### ISSUE TITLE
Not working, always giving error: Team Server returned unexpected response code 'Redirect' for resource

### ISSUE THREAD

**Issue by rpresser** [Contrast-Security-OSS/contrast-sdk-dotnet#15]
No matter what method I call, I always get an error similar to this one:
```
Contrast.ContrastApiException
  HResult=0x80131500
  Message=Team Server returned unexpected response code 'Redirect' for resource: 'api/ng/profile/organizations/'
  Source=ContrastRestClient
  StackTrace:
   at Contrast.Http.ContrastRestClient.CheckResponseStatusCode(String apiEndpoint, HttpStatusCode statusCode)
   at Contrast.Http.ContrastRestClient.GetResponseStream(String apiEndpoint)
   at Contrast.Client.GetResponseAndDeserialize[T](String endpoint)
   at Contrast.Client.GetOrganizations()
   at Contrast_app_machine_grid.Program.Letstry() in C:\Users\rpresser\source\repos\Contrast_app_machine_grid\Program.cs:line 26
   at Contrast_app_machine_grid.Program.Main(String[] args) in C:\Users\rpresser\source\repos\Contrast_app_machine_grid\Program.cs:line 13
```

Here is the code for my sample program. Redacted credentials of course; but I've triple-checked them, and they're working with the Visual Studio plugin.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Contrast_app_machine_grid
{
    class Program
    {
        static void Main(string[] args)
        {
            Letstry();
        }

        static void Letstry()
        {
            string apikey = "--redacted--";
            string username = "rpresser";
            string servicekey = "--redacted--";
            string teamserverurl = "https://app.contrastsecurity.com/Contrast/";

            Contrast.Client client = new Contrast.Client(username, servicekey, apikey, teamserverurl);

            var x = client.GetOrganizations();  // error thrown here

        }
    }
}
```

**Comment by rpresser** [comment]
Stupid me. Username needs to be my full email address. Problem has stopped.
